---
- name: prueba de lint 
  hosts: all
  tasks:

    - name: Use command instead of module
      command: echo "Hello"
      
    - name: Say Hello
      debug:
        msg: "Hello, world!"

    - name: "{{ ansible_hostname }}  {{ ansible_date_time.date }}"
      ansible.builtin.imprimir:
        msg: "Fecha: {{ ansible_date_time.date }} nombre: {{ ansible_hostname  }}."

    - name: Say Hello 2
      debug:
        msg: "Hello, world 2!"