---
- name: prueba de lint 
  hosts: all
  tasks:

    - name: Use command instead of module
      command: echo "Hello"

    - name: say hello
      debug:
        msg: "Hello, world!"

    - name: "{{ ansible_hostname }}  {{ ansible_date_time.date }}"
      ansible.builtin.debug:
        msg: "Fecha: {{ ansible_date_time.date }} nombre: {{ ansible_hostname  }}."

    - name: Say Hello 2
      debug:
        msg: "Hello, world 2!"

    - name: Use command instead of module 2
      command: echo "Hello 2"